- name: Ensure htpasswd-related utilities are installed (Debian).
  apt: "pkg={{ item }} state=present"
  with_items:
    - apache2-utils
    - nginx
    - python-passlib

- name: Enable default Vhost
  template: src=nginx-default.j2 dest=/etc/nginx/sites-available/default

- name: Create htpasswd User
  htpasswd: path=/etc/nginx/htpasswd.users name=kibanaadmin password=kibana owner=root group=root mode=0644
  notify: restart nginx

- name: Ensure SSL certificates have the correct directories
  file: path=/etc/nginx/ssl owner=root group=root mode=0755 state=directory

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Ile-de-France/L=Paris/O=IT/CN={{ fqdnOrPublicIp }}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt
  notify: reload nginx

